apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: install-pattern
  namespace: {{ .Values.pipelineNamespace }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
spec:
  description: Install a validated pattern on the target cluster
  params:
  workspaces:
    - name: pattern-repo
    - name: kubeconfig
  results:
    - name: outcome
  steps:
    - name: install-pattern
      image: quay.io/validatedpatterns/utility-container
      env:
        - name: KUBECONFIG
          value: $(workspaces.kubeconfig.path)/kubeconfig
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        trap 'echo -n failed > "$(results.outcome.path)"' ERR
        cd $(workspaces.pattern-repo.path)


        # This is some workaround for git-clone
        # git config --global --add safe.directory $(workspaces.pattern-repo.path)
        # git checkout -B pipeline_test origin/pipeline_test


        # This is some workaround for Tekton injecting some KUBERNETES_* env vars
        unset KUBERNETES_SERVICE_HOST

        # Install the pattern
        ./pattern.sh make install

        # If we reach here, everything succeeded
        echo -n success > "$(results.outcome.path)"
