apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: must-gather
  namespace: {{ .Values.pipelineNamespace }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
spec:
  description: Collect must-gather from a failed cluster
  params:
    - name: cluster-name
      type: string
      default: ""
  workspaces:
    - name: kubeconfig
    - name: must-gather
  results:
    - name: outcome
  steps:
    - name: must-gather
      image: {{ .Values.pipelines.defaults.utilityContainerImg }}
      env:
        - name: KUBECONFIG
          value: $(workspaces.kubeconfig.path)/$(params.cluster-name)-kubeconfig
      script: |
        #!/usr/bin/env bash
        trap 'echo -n failed > "$(results.outcome.path)"' ERR
        # TODO: collect must-gather from failed cluster
        DESTDIR= $(workspaces.must-gather.path)/$(params.cluster-name)
        oc adm must-gather --image-stream=openshift/must-gather --image={{ .Values.pipelines.defaults.mustGatherImg }} --dest-dir="${DESTDIR}"
        echo -n success > "$(results.outcome.path)"
