apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: upload-must-gather
  namespace: {{ .Values.pipelineNamespace }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
spec:
  description: Upload must-gather archive

  steps:
    - name: upload-must-gathers
      image: {{ .Values.pipelines.defaults.utilityContainerImg }}
      script: |
        #!/usr/bin/env bash
        # TODO: upload must-gather archive
        echo "upload must-gather"
