apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: upload-test-results
  namespace: {{ .Values.pipelineNamespace }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
spec:
  description: Upload interop test results
  params:
  steps:
    - name: upload-tests
      image: {{ .Values.pipelines.defaults.utilityContainerImg }}
      script: |
        #!/usr/bin/env bash
        # TODO: upload test results artifact
        echo "upload test results"
